# Seminar 2


Matrix norms, unitary matrices

In [ ]:
import numpy as np

### Useful tools using numpy


In [ ]:
n, m = 3, 3

In [ ]:
#Generate random matrix from N(0, 1)
np.random.normal(size=(n,m))

array([[-1.70582563, -0.12652267, -0.77566702],
       [ 2.23650683, -0.3900103 , -0.72988584],
       [-0.92945329,  1.23676149,  1.68089367]])

In [ ]:
# Create the n×n identity matrix I.

np.identity(n)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# defining your own matrix

np.array([[4,  8,  15],
           [16, 23, 42],
           [0,  0,  0]])

array([[ 4,  8, 15],
       [16, 23, 42],
       [ 0,  0,  0]])

In [ ]:
# Generate random samples from N(0, 1)
# Matrix multiplication: A @ B (matrix–matrix) or A @ x (matrix–vector)

a = np.random.normal(size=(n,m))
b = np.random.normal(size=(n,m))
x = np.random.normal(size=(n,))
print(np.matmul(a, b))
print()
print(np.matmul(a, x))


[[ 0.43027203  0.02616388  1.5334068 ]
 [ 0.00353183 -0.6393471   0.57089205]
 [ 2.53384358  0.51734497  1.49414279]]

[ 1.7755594  -0.14653985  2.13601041]


In [ ]:
a@b

array([[ 0.43027203,  0.02616388,  1.5334068 ],
       [ 0.00353183, -0.6393471 ,  0.57089205],
       [ 2.53384358,  0.51734497,  1.49414279]])

In [ ]:
a@x

array([ 1.7755594 , -0.14653985,  2.13601041])

In [ ]:
b=np.array([[4,  8,  15],
           [16, 23, 42],
           [0,  0,  0]])
for i,j in enumerate(b):
    print(i, j[0])

0 4
1 16
2 0


In [ ]:
#or
b[:,0]

array([ 4, 16,  0])

# Matrix Norms Calculation


- **$p=1$ (max column sum):**
  $$
  \|A\|_{1} \;=\; \max_{1\le j\le m} \sum_{i=1}^{n} |a_{ij}|.
  $$
- **$p=\infty$ (max row sum):**
  $$
  \|A\|_{\infty} \;=\; \max_{1\le i\le n} \sum_{j=1}^{m} |a_{ij}|.
  $$
- **$p=2$ (spectral norm):**
  $$
  \|A\|_{2} \;=\; \sigma_{\max}(A)
  \;=\; \sqrt{\lambda_{\max}(A^{\top}A)}.
  $$

**Frobenius norm (matrix but not operator norm):**
$$
\|A\|_{F} \;=\; \sqrt{\sum_{i,j} a_{ij}^{2}}
\;=\; \sqrt{\mathrm{tr}(A^{\top}A)}.
$$



## Exercise 1 — $\|A\|_{1}$ and $\|A\|_{\infty}$

Let
$$
A=\begin{bmatrix}
1 & -2\\
0 & 3
\end{bmatrix}.
$$

Compute $\|A\|_{1}$ and $\|A\|_{\infty}$



## **Solution**




- Column sums: column 1: $\lvert1\rvert+\lvert0\rvert=1$, column 2: $\lvert-2\rvert+\lvert3\rvert=5$.  
  Hence
  $$
  \|A\|_{1}=\max\{1,5\}=5.
  $$

- Row sums: row 1: $\lvert1\rvert+\lvert-2\rvert=3$, row 2: $\lvert0\rvert+\lvert3\rvert=3$.  
  Hence
  $$
  \|A\|_{\infty}=\max\{3,3\}=3.
  $$



## Exercise 2 — Compute $\|A\|_{2}$ via $A^{\top}A$

Let
$$
A=\begin{bmatrix}
1 & 2\\
0 & 1
\end{bmatrix}.
$$

Compute the spectral norm $\|A\|_{2}=\sqrt{\lambda_{\max}(A^{\top}A)}$.


## **Hint**

**Eigenvalues and Characteristic Polynomial**

Scalar $\lambda$ is an eigenvalue of $A$ if there exists a nonzero vector $v$ such that
$$
Av=\lambda v,\qquad v\neq 0.
$$

**Characteristic polynomial:**
$$
p(\lambda)=\det(A-\lambda I).
$$
**Eigenvalues** are the roots of $p(\lambda)=0$.

**$(2\times 2)$ closed form.** If
$$
A=\begin{bmatrix} a & b \\ c & d \end{bmatrix},
$$
then
$$
\lambda_{1,2}=\frac{\operatorname{tr}A \pm \sqrt{(\operatorname{tr}A)^2-4\det A}}{2},
\qquad
\operatorname{tr}A=a+d,\;\; \det A=ad-bc.
$$


## **Solution**

$$
A^{\top}A
=\begin{bmatrix}1&0\\ 2&1\end{bmatrix}
\begin{bmatrix}1&2\\ 0&1\end{bmatrix}
=\begin{bmatrix}1&2\\ 2&5\end{bmatrix}.
$$

Eigenvalues of $\begin{bmatrix}1&2\\ 2&5\end{bmatrix}$ are
$$
\lambda_{\pm}=\frac{(1+5)\pm\sqrt{(1-5)^2+4\cdot 2^2}}{2}
=\frac{6\pm\sqrt{32}}{2}
=3\pm 2\sqrt{2}.
$$
Thus $\lambda_{\max}=3+2\sqrt{2}\approx 5.8284$, and
$$
\|A\|_{2}=\sqrt{\lambda_{\max}}\approx \sqrt{5.8284}\approx 2.4142.
$$

## Exercise 3 — Quick spectral-norm check

Let
$$
D=\begin{bmatrix}
3&0&0\\
0&-1&0\\
0&0&2
\end{bmatrix}.
$$

Compute $\|D\|_{2}$.



##**Solution**

For diagonal $D$, singular values are the absolute diagonal entries $(3,1,2)$. Hence
$$
\|D\|_{2}=\max\{3,1,2\}=3.
$$

## Exercise 4 — Frobenius norm

Let
$$
B=\begin{bmatrix}
1 & -2 & 2\\
0 & 3 & -1
\end{bmatrix}.
$$

Compute $\|B\|_{F}$ and verify $\|B\|_{F}=\sqrt{\mathrm{tr}(B^{\top}B)}$.



## **Solution**

**Sum of squares**
$$
1^2+(-2)^2+2^2+0^2+3^2+(-1)^2
=1+4+4+0+9+1=19.
$$
So
$$
\|B\|_{F}=\sqrt{19}\approx 4.3589.
$$

**Via** $\sqrt{\mathrm{tr}(B^\top B)}$

Compute $B^\top$
$$
B^\top=\begin{bmatrix}
1 & 0\\
-2 & 3\\
2 & -1
\end{bmatrix}.
$$

Multiply $B^\top B$ (show every dot product)

Columns of $B$:
$$
c_1=\begin{bmatrix}1\\0\end{bmatrix},\quad
c_2=\begin{bmatrix}-2\\3\end{bmatrix},\quad
c_3=\begin{bmatrix}2\\-1\end{bmatrix}.
$$

Rows of $B^\top$:
$$
r_1=\begin{bmatrix}1 & 0\end{bmatrix},\quad
r_2=\begin{bmatrix}-2 & 3\end{bmatrix},\quad
r_3=\begin{bmatrix}2 & -1\end{bmatrix}.
$$

Now each entry $(B^\top B)_{ij}=r_i\cdot c_j$:
$$
\begin{aligned}
(B^\top B)_{11}&=r_1\cdot c_1=1\cdot1+0\cdot0=1,\\
(B^\top B)_{12}&=r_1\cdot c_2=1\cdot(-2)+0\cdot3=-2,\\
(B^\top B)_{13}&=r_1\cdot c_3=1\cdot2+0\cdot(-1)=2,\\[4pt]
(B^\top B)_{21}&=r_2\cdot c_1=(-2)\cdot1+3\cdot0=-2,\\
(B^\top B)_{22}&=r_2\cdot c_2=(-2)\cdot(-2)+3\cdot3=4+9=13,\\
(B^\top B)_{23}&=r_2\cdot c_3=(-2)\cdot2+3\cdot(-1)=-4-3=-7,\\[4pt]
(B^\top B)_{31}&=r_3\cdot c_1=2\cdot1+(-1)\cdot0=2,\\
(B^\top B)_{32}&=r_3\cdot c_2=2\cdot(-2)+(-1)\cdot3=-4-3=-7,\\
(B^\top B)_{33}&=r_3\cdot c_3=2\cdot2+(-1)\cdot(-1)=4+1=5.
\end{aligned}
$$

Therefore
$$
B^\top B=\begin{bmatrix}
1 & -2 & 2\\
-2 & 13 & -7\\
2 & -7 & 5
\end{bmatrix}.
$$

Take the trace
$$
\mathrm{tr}(B^\top B)=1+13+5=19.
$$

Conclude
$$
\boxed{\ \|B\|_F=\sqrt{\mathrm{tr}(B^\top B)}=\sqrt{19}\ }.
$$



# Matrix Norms Calculation with python

Important case of operator norms are matrix p-norms, which are defined for $\|\cdot\|_* = \|\cdot\|_{**} = \|\cdot\|_p$

Among all p-norms three norms are the most common ones:

$p = 1, \quad \Vert A \Vert_{1} = \displaystyle{\max_j \sum_{i=1}^n} |a_{ij}|$

$p = 2, \quad$ spectral norm, denoted by $\Vert A \Vert_2$

$p = \infty, \quad \Vert A \Vert_{\infty} = \displaystyle{\max_i \sum_{j=1}^m} |a_{ij}|$

Let us work with = 1 and inf now.

### Lets write our own functions to calculate 0 and inf norms:


In [ ]:
def p_1_norm(a):
    n,m = a.shape
    max = 0
    for i in range(m):
        max = np.max([np.sum(np.abs(a[:,[i]])), max])
    return max

def p_inf_norm(a):
    n,m = a.shape
    max = 0
    for i in range(n):
        max = np.max([np.sum(np.abs(a[i])), max])
    return max

m, n = 3, 3
a = np.random.normal(size=(n,m)) #Random n x m matrix
print(a)
print("p_1 norm: ", p_1_norm(a))
print("p_inf norm: ", p_inf_norm(a))

[[-1.44699689 -1.53471388  0.43762615]
 [-0.65175735  0.1924952   0.15954042]
 [-0.5610403   0.4727873  -0.25184526]]
p_1 norm:  2.659794534508114
p_inf norm:  3.4193369151172304


### Now, make up a toy example matrix for which these two are equal:

In [ ]:
b = np.array([[1, 0, 0],
               [0, 1, 0],
               [0, 0, 1]])

print("p_1 norm: ", p_1_norm(b))
print("p_inf norm: ", p_inf_norm(b))
print(p_1_norm(b) == p_inf_norm(b))

p_1 norm:  1
p_inf norm:  1
True


### Creative task: invent your own matrix norm and check that it satisfies three norm requirements

$\Vert \cdot \Vert$ is called a **matrix norm** if it is a vector norm on the vector space of $n \times m$ matrices and:

$\|A\| \geq 0$ and if $\|A\| = 0$ then $A = O$

$\|\alpha A\| = |\alpha| \|A\|$

$\|A+B\| \leq \|A\| + \|B\|$ (triangle inequality)


Additionally some norms can satisfy the *submultiplicative property*:
$\Vert A B \Vert \leq \Vert A \Vert \Vert B \Vert$

## **Solution**

In [ ]:
# Explanation: Example of a non‑norm: sum of absolute diagonal entries (fails ||A||=0 ⇒ A=0).
def super_norm(a):

    n,m = a.shape
    sum = 0
    for i in range(n):
        sum += np.abs(a[i,i])

    return sum

In [ ]:
n, m = 50, 50

Now, lets check all requirements. **Attention!** If some conditions seem to not work, recall previous lecture to understand and fix the problem

In [ ]:
# Explanation: Generate random samples from N(0, 1); shapes determine vectors/matrices. | Check nonnegativity: a norm should never be negative.
is_nonnegative = True

for i in range(42):
    a = np.random.normal(size=(n,m))

    if super_norm(a) < 0:
        is_nonnegative = False

print("is_nonnegative: ", is_nonnegative)

is_nonnegative:  True


In [ ]:
# Check zero property: ||0|| = 0
respects_zero = True

a = np.zeros((n,m))

if super_norm(a) != 0:
    respects_zero = False

print("respects_zero: ", respects_zero)

respects_zero:  True


In [ ]:
# Check homogeneity: ||αA|| = |α|·||A||
respects_scalar_mult = True

for i in range(42):
    a = np.random.normal(size=(n,m))
    alpha = np.abs(np.random.normal())

    if np.abs(super_norm(alpha * a) - alpha * super_norm(a)) > 0.001:
        respects_scalar_mult = False

print("respects_scalar_mult: ", respects_scalar_mult)

respects_scalar_mult:  True


In [ ]:
# Check triangle inequality: ||A+B|| ≤ ||A|| + ||B||.
triangle_inequality = True

for i in range(42):
    a = np.random.normal(size=(n,m))
    b = np.random.normal(size=(n,m))

    if super_norm(a + b) > super_norm(a) + super_norm(b):
        triangle_inequality = False

print("triangle_inequality: ", triangle_inequality)

triangle_inequality:  True


In [ ]:
# check submultiplicativity ||AB|| ≤ ||A||·||B||

is_submultiplicative = True

for i in range(42):
    a = np.random.normal(size=(n,m))
    b = np.random.normal(size=(n,m))

    if super_norm(np.matmul(a, b)) > super_norm(a) * super_norm(b):
        is_submultiplicative = False

print("is_submultiplicative: ", is_submultiplicative)

is_submultiplicative:  True


## **Householder Martices**

Householder matrix is the matrix of the form:
$$H \equiv H(v) = I - 2 vv^*,$$
where $v$ is an $n \times 1$ column and $v^* v = 1$.

It is also a reflection:
$$ Hx = x - 2(v^* x) v$$

**Attention!** If it does not work, remember about vector norm

# Core formulas
**Householder matrix.** A Householder matrix is ($H=I-2vv^{*}$) with ($|v|_2=1$); it reflects a vector across the hyperplane orthogonal to (v) (flips the component along (v), leaves the rest unchanged). It is both Hermitian and Unitary: ($H^{*}=H$) and ($H^{*}H=I$).

**Hermitian matrix.** A matrix is **Hermitian** if ($A^{*}=A$), which guarantees real eigenvalues and an orthonormal eigenbasis.

What is a **unitary matrix**?

A matrix (U) (real or complex) is **unitary** if it preserves lengths and angles:
$$
U^{*}U=I \quad(\text{equivalently } U^{-1}=U^{*}).
$$

**Unitary and involutory properties of (H)**

For the Householder reflector
$$
H=I-2vv^{*},\qquad v^{*}v=1,
$$
we have two key properties:

1. **Unitary**:
   $$
   H^{*}H=(I-2vv^{*})^{*}(I-2vv^{*})=(I-2vv^{*})(I-2vv^{*})=I,
   $$
   since ($v^{*}v=1$). So (H) preserves lengths: ($|Hx|_2=|x|_2$).

2. **Involutory** (its own inverse):
   $$
   H^2=(I-2vv^{*})^2=I-4vv^{*}+4v(v^{*}v)v^{*}=I.
   $$
   Involutory means ($H^{-1}=H$); applying the reflector twice gives you back the original vector.

(Additionally, (H) is **Hermitian**: ($H^{*}=H$).)



**Vector 2-norm and normalization**
   $$
   \|v\|_2=\sqrt{\sum_i |v_i|^2},\qquad \hat v=\frac{v}{\|v\|_2}\ \ (\text{if }\|v\|_2\neq 0).
   $$

**Hermitian conjugate**
   $$
   A^{*}=\overline{A}^{\top},\quad \text{in }\mathbb{R}:\ A^{*}=A^{\top}.
   $$

**Householder matrix**
   $$
   H(v)=I-2\,vv^{*},\qquad v^{*}v=1.
   $$

**Reflection action**
   $$
   Hx=(I-2vv^{*})x=x-2\,(v^{*}x)\,v.
   $$

**Hermitian, unitary, and involutory properties of $H$**
   $$
   H^{*}=H,\qquad H^{*}H=I,\qquad H^2=I.
   $$



## Numerical exercises

## Exercise 1 — Compute сonjugate transpose of :

1.
$$
x=\begin{bmatrix}2\\ -1\\ 3\end{bmatrix}\in\mathbb{R}^{3\times 1}.
$$

2.
$$
z=\begin{bmatrix}3+2i\\ -i\\ 1-4i\end{bmatrix}\in\mathbb{C}^{3\times 1}.
$$

3.
$$
A=\begin{bmatrix}
1 & -2 & 0\\
4 & 3 & -5
\end{bmatrix}\in\mathbb{R}^{2\times 3}.
$$

4.
$$
B=\begin{bmatrix}
1+i & -2i\\
3-4i & 5
\end{bmatrix}\in\mathbb{C}^{2\times 2}.
$$


## **Solution**

### 1.

$x$ is real, so $\overline{x}=x$.

Turn the $3\times 1$ column into a $1\times 3$ row:
$$
x^{*}=\overline{x}^{\top}=x^{\top}=\begin{bmatrix}2 & -1 & 3\end{bmatrix}.
$$

### 2.
$$
\overline{z}=\begin{bmatrix}3-2i\\ i\\ 1+4i\end{bmatrix}.
$$

$$
z^{*}=\overline{z}^{\top}=\begin{bmatrix}3-2i & i & 1+4i\end{bmatrix}.
$$

## 3.

$A$ is real, so $\overline{A}=A$.

$$
A^{*}=A^{\top}=
\begin{bmatrix}
1 & 4\
-2 & 3\
0 & -5
\end{bmatrix}.
$$

## 4.

$$
\overline{B}=\begin{bmatrix}
1-i & 2i\\
3+4i & 5
\end{bmatrix}.
$$

$$
B^{*}=\overline{B}^{\top}
=\begin{bmatrix}
1-i & 3+4i\\
2i & 5
\end{bmatrix}.
$$

## Exercise 2 — Build a Householder reflector from a given $v$

Given $v=\begin{bmatrix}2\\-1\\2\end{bmatrix}$. Construct
$$
H=I-2\hat v \hat v^{*},\qquad \hat v=\frac{v}{\|v\|_2}.
$$

## **Solution**

### Compute the 2-norm of $v$
$$
\|v\|_2 \;=\; \sqrt{2^2+(-1)^2+2^2} \;=\; \sqrt{9} \;=\; 3.
$$

### Normalize $v$
$$
\hat v \;=\; \frac{v}{\|v\|_2} \;=\; \frac{1}{3}\begin{bmatrix}2\\-1\\2\end{bmatrix}
\;=\; \begin{bmatrix}\tfrac{2}{3}\\[2pt]-\tfrac{1}{3}\\[2pt]\tfrac{2}{3}\end{bmatrix}.
$$

### Form the outer product $\hat v\hat v^{*}$
Since entries are real, $\,\hat v^{*}=\hat v^{\top}\,$ and
$$
\hat v\hat v^{*}
=\begin{bmatrix}\tfrac{2}{3}\\ -\tfrac{1}{3}\\ \tfrac{2}{3}\end{bmatrix}
\begin{bmatrix}\tfrac{2}{3} & -\tfrac{1}{3} & \tfrac{2}{3}\end{bmatrix}
=\frac{1}{9}
\begin{bmatrix}
4 & -2 & 4\\
-2 & 1 & -2\\
4 & -2 & 4
\end{bmatrix}.
$$

### Compute $2\,\hat v\hat v^{*}$ and subtract from $I$
$$
2\,\hat v\hat v^{*}
=\frac{2}{9}
\begin{bmatrix}
4 & -2 & 4\\
-2 & 1 & -2\\
4 & -2 & 4
\end{bmatrix}
=\frac{1}{9}
\begin{bmatrix}
8 & -4 & 8\\
-4 & 2 & -4\\
8 & -4 & 8
\end{bmatrix}.
$$
Therefore
$$
H \;=\; I-2\,\hat v\hat v^{*}
=\begin{bmatrix}
1-\tfrac{8}{9} & \tfrac{4}{9} & -\tfrac{8}{9}\\
\tfrac{4}{9} & 1-\tfrac{2}{9} & \tfrac{4}{9}\\
-\tfrac{8}{9} & \tfrac{4}{9} & 1-\tfrac{8}{9}
\end{bmatrix}
=\frac{1}{9}
\begin{bmatrix}
1 & 4 & -8\\
4 & 7 & 4\\
-8 & 4 & 1
\end{bmatrix}.
$$


##Exercise 3 — Build Householder matrix and verify Hermitian and unitary.
Let $v=\dfrac{1}{\sqrt2}\begin{bmatrix}1\\ i\end{bmatrix}$. Build $H=I-2vv^{*}$ and verify Hermitian and unitary.



## **Solution**

Check that $v$ is unit‐norm
$$
\|v\|_2^2=v^{*}v=\frac{1}{2}\big(|1|^2+|i|^2\big)=\frac{1}{2}(1+1)=1.
$$

Compute the conjugate transpose $v^{*}$
$$
v^{*}=\left(\frac{1}{\sqrt{2}}\begin{bmatrix}1\\ i\end{bmatrix}\right)^{*}
=\frac{1}{\sqrt{2}}\begin{bmatrix}1 & -i\end{bmatrix}.
$$

Compute $v v^{*}$
$$
v v^{*}
=\frac{1}{2}
\begin{bmatrix}1\\ i\end{bmatrix}
\begin{bmatrix}1 & -i\end{bmatrix}
=\frac{1}{2}
\begin{bmatrix}
1 & -i\\
i & 1
\end{bmatrix}.
$$

Build the Householder matrix $H$
$$
2\,v v^{*}=
\begin{bmatrix}
1 & -i\\
i & 1
\end{bmatrix},
\qquad
H=I-2\,v v^{*}
=\begin{bmatrix}
1 & 0\\ 0 & 1
\end{bmatrix}
-
\begin{bmatrix}
1 & -i\\
i & 1
\end{bmatrix}
=
\begin{bmatrix}
0 & i\\
-i & 0
\end{bmatrix}.
$$

Verify **Hermitian**: $H^{*}=H$
Take conjugate transpose:
$$
H^{*}
=\begin{bmatrix}
0 & i\\
-i & 0
\end{bmatrix}^{*}
=\begin{bmatrix}
0 & -i\\
i & 0
\end{bmatrix}^{\top}
=\begin{bmatrix}
0 & i\\
-i & 0
\end{bmatrix}
=H.
$$

Verify **Unitary** (equivalently, involutory): $H^{*}H=I$ and $H^2=I$
Compute $H^2$ directly:
$$
H^2=
\begin{bmatrix}
0 & i\\
-i & 0
\end{bmatrix}
\begin{bmatrix}
0 & i\\
-i & 0
\end{bmatrix}
=
\begin{bmatrix}
i\cdot(-i) & 0\\
0 & (-i)\cdot i
\end{bmatrix}
=
\begin{bmatrix}
1 & 0\\
0 & 1
\end{bmatrix}
=I.
$$
Hence $H^{-1}=H$ and also $H^{*}H=I$ (so $H$ is unitary).


## Exercise 4 — Unitary (orthogonality) check
Let
$$
U=\frac{1}{\sqrt2}\begin{bmatrix}
1 & 1\\
1 & -1
\end{bmatrix}.
$$
Show that $U$ is unitary (orthogonal in $\mathbb{R}$).



## **Solution**

$$
U^{*}U=U^{\top}U=\frac{1}{2}
\begin{bmatrix}1&1\\ 1&-1\end{bmatrix}
\begin{bmatrix}1&1\\ 1&-1\end{bmatrix}
=\frac{1}{2}\begin{bmatrix}2&0\\ 0&2\end{bmatrix}=I.
$$

## Exercise 5 — Check properties (Hermitian and Unitary)
$$
B=\begin{bmatrix}
4&0\\
0&1
\end{bmatrix}.
$$




## **Solution**


$B^{*}=B$ ⇒ Hermitian. But
$$
B^{*}B=B^2=\begin{bmatrix}16&0\\ 0&1\end{bmatrix}\neq I,
$$
so not unitary.

## Exercise 5 — Check unitarity/orthogonality
Given $w=\begin{bmatrix}1\\1\end{bmatrix}$ (not unit). Compare
$$
\tilde H = I-2\,w w^{\top}
\quad\text{and}\quad
H=I-2\,\hat w \hat w^{\top},\ \ \hat w=\frac{w}{\|w\|_2}.
$$




## **Solution**


$\|w\|_2=\sqrt{2}$, $\hat w=\tfrac{1}{\sqrt2}\begin{bmatrix}1\\1\end{bmatrix}$.
$$
\tilde H = I-2\begin{bmatrix}1\\1\end{bmatrix}\begin{bmatrix}1&1\end{bmatrix}
=
\begin{bmatrix}-1&-2\\ -2&-1\end{bmatrix}\ \Rightarrow\
\tilde H^{\top}\tilde H\neq I,
$$
while
$$
H = I-2\hat w \hat w^{\top}
= I - 2\cdot \frac{1}{2}
\begin{bmatrix}1&1\\ 1&1\end{bmatrix}
=
\begin{bmatrix}0&-1\\ -1&0\end{bmatrix},
\qquad
H^{\top}H=I.
$$
Conclusion: normalizing $v$ is necessary for unitarity/orthogonality.